import {
  Bell,
  CircleQuestionMark,
  Cpu,
  FileChartColumn,
  FileText,
  HardDrive,
  Layers,
  LayoutDashboard,
  User,
  User2Icon,
  UserCheck,
  Users,
  UserStar,
} from "lucide-react";

const navigationItems = [
  {
    name: "Dashboard",
    href: "/dashboard",
    icon: LayoutDashboard,
    isCollapsible: false,
    roles: ["superadmin", "admin", "user"],
  },
  {
    name: "Groups",
    href: "groups",
    icon: Layers,
    isCollapsible: true,
    roles: ["superadmin"],
    collapse: [
      { name: "All Groups", href: "/groups/all", icon: User2Icon },
      { name: "Create Group", href: "/groups/create", icon: UserCheck },
    ],
  },
  {
    name: "Devices",
    href: "/devices",
    isCollapsible: false,
    icon: Cpu,
    roles: ["superadmin", "admin", "user"],
  },
  {
    name: "Courses",
    href: "/courses",
    icon: FileChartColumn,
    roles: ["superadmin", "admin", "user"],
  },
  {
    name: "Students Overview",
    href: "/students-overview",
    icon: UserStar,
    isCollapsible: false,
    roles: ["superadmin", "admin"],
  },
  {
    name: "Users",
    href: "/users",
    isCollapsible: false,
    icon: Users,
    roles: ["superadmin", "admin"],
  },
  {
    name: "Firmwares",
    href: "/firmwares",
    isCollapsible: false,
    icon: HardDrive,
    roles: ["superadmin"],
  },
  {
    name: "Create User",
    href: "/create-user",
    isCollapsible: false,
    icon: UserCheck,
    roles: ["superadmin"],
  },
  {
    name: "Notifications",
    href: "/notifications",
    isCollapsible: false,
    icon: Bell,
    roles: ["superadmin", "admin", "user"],
  },
  {
    name: "System Logs",
    href: "/system-logs",
    isCollapsible: false,
    icon: FileText,
    roles: ["superadmin"],
  },
  {
    name: "Support",
    href: "/support",
    icon: CircleQuestionMark,
    isCollapsible: false,
    roles: ["superadmin"],
  },
  {
    name: "Profile",
    isCollapsible: false,
    href: "/profile",
    icon: User,
    roles: ["superadmin", "admin", "user"],
  },
];

export default navigationItems;
