name: Deploy to VPS Hosting
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Now use Jenkins for deployment
      - name: Trigger Jenkins Job
        run: |
          echo "Triggering Jenkins Job..."

      # # Checkout repository
      # - name: Checkout repository
      #   uses: actions/checkout@v4

      # # Setup Node.js
      # - name: Setup Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #       node-version: 20
      #       cache: npm

      # # Install pnpm
      # - name: Install pnpm
      #   uses: pnpm/action-setup@v3
      #   with:
      #       version: 9

      # # Install dependencies using pnpm
      # - name: Install dependencies
      #   run: pnpm install --frozen-lockfile

      # # Run ESLint
      # - name: Run ESLint
      #   run: npm run lint

      # # Build project
      # - name: Build project
      #   run: npm run build

      # # Create .env file
      # - name: Create .env file
      #   env:
      #       ENV_FILE: ${{ secrets.ENV_FILE }}
      #   run: |
      #       echo "${ENV_FILE}" > .env
      #       echo "Environment file created."

      # # Deploy to VPS via SSH with password
      # - name: Deploy to VPS Hosting
      #   uses: appleboy/ssh-action@master
      #   with:
      #       host: ${{ secrets.VPS_HOST }}
      #       username: ${{ secrets.VPS_USER }}
      #       password: ${{ secrets.VPS_PASSWORD }}
      #       port: 22
      #       script: |
      #           # project directory
      #           DIR="/home/apps/client"

      #           # Path
      #           export PATH= /root/.nvm/versions/node/v22.19.0/bin:\$PATH

      #           # Check if PM2 process exists and stop it
      #           if pm2 list | grep -q "client"; then
      #             pm2 stop client
      #           #   pm2 delete client
      #           fi

      #           # Delete if exists
      #           if [ -d "$DIR" ]; then
      #               sudo rm -rf "$DIR"
      #               echo "Deleted existing directory: $DIR"
      #           fi

      #           # Create directory
      #           sudo mkdir -p "$DIR"
      #           echo "Directory $DIR created."

      #           cd "$DIR"

      #           # Clone the repository
      #           sudo git clone https://github.com/md-rejoyan-islam/SUST_EEE_IOT_CLIENT.git .

      #           # Create .env file with configs
      #           echo "${{ secrets.ENV_FILE }}" | sudo tee "$DIR/.env" > /dev/null
      #           echo "Environment file created."

      #           # Install dependencies
      #           npm install

      #           # Build the project
      #           npm run build

      #           # Update pm2 configuration
      #           # pm2 start --name client -- run start
      #           pm2 reload client

      #           # Update Nginx configuration
      #           systemctl reload nginx
